### ISSUE TITLE
priority_rewrite.py modifies a dict's keys while iterating, not allowed under Python 3.8

### ISSUE THREAD

**Issue by SchallerSpace** [pirl-lpl/hirise-tools#13]
In `priority_rewrite.py`, there's a modification to a dict's keys while iterating:

```python
    for k in count.keys():
        if k in reset:
            count[reset[k]] = count[k]
            del count[k]
```

Apparently this is not allowed under Python 3.8, at least based on this result when googling the error ("RuntimeError: dictionary keys changed during iteration") - https://community.atlassian.com/t5/Jira-Core-questions/RuntimeError-dictionary-keys-changed-during-iteration-when/qaq-p/1245641

To reproduce:

1. Set up an environment that uses Python 3.8.
2. Run the CIPP tools unit tests: `python -m unittest` (or just `make` in this package, very nice).

Error:

```
python -m unittest
.....E............
======================================================================
ERROR: test_priority_rewrite (test_priority_rewrite.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/schaller/Sandbox/HiRISE/hirise-tools/CIPP/test_priority_rewrite.py", line 92, in test_priority_rewrite
    pr.priority_rewrite(r, '800:700')[0])
  File "/Users/schaller/Sandbox/HiRISE/hirise-tools/CIPP/priority_rewrite.py", line 73, in priority_rewrite
    for k in count.keys():
RuntimeError: dictionary keys changed during iteration

----------------------------------------------------------------------
Ran 18 tests in 0.026s

FAILED (errors=1)
```

The very easy workaround is to use Python 3.7; in fact, I only accidentally used 3.8 because I didn't realize `conda` would use 3.8 when creating a new environment—I had intended to be using 3.7. I honestly have no idea whether 3.7 should be the target or 3.8; I'm not familiar enough with the state of Python to know the preferred solution here.

Three cheers for unit tests, though.

**Comment by rbeyer** [comment]
Okay, yay tests.

That being said, the test harness here is not very sophisticated, and doesn't do multiple Python version testing (maybe time to set that up here).  I have just been treating this as a little toy, and maybe its time to upgrade my/our approach here (which usually happens when people beyond me are actually using it).

I don't do a lot of dev in 3.8, so that they tightened this up is not surprising.  I can probably fix it, if that's the only thing that's broken.

But it isn't.  :(

OP is correct,  using Python 3.7.6 (the default Python 3.7 from conda at this moment, if one does `conda create -n py37 python=3.7`) does allow the test suite to finish without errors.  However, if one uses Python 3.7.0 or Python 3.6.7, there are *different* errors.  Sigh.

What should we be compatible with?  https://www.python.org/downloads/ shows the status of the various Python releases.  We can certainly pick our poison, but I will let you know that the PlanetaryPy project has decided to aim their software development to support Python 3.6 and higher (3.5 compatibility was decided against since it will EOL this September).  This means that you write your Python in such a way that it passes tests on 3.6, 3.7, 3.8, etc. so that no matter what someone is using, it 'just works' for them, and that's probably what we should move to here.

At the moment, just using the 3.7.* will make things work.  I'll try and find some time to get the other versions to work, too.

**Comment by SchallerSpace** [comment]
The tests now pass 18/18 for
- 3.6.10
- 3.7.6
- 3.8.2

I think this can be closed.
